/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.BoolConfigItem;
import com.imwyh.harbor.client.model.IntegerConfigItem;
import com.imwyh.harbor.client.model.StringConfigItem;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ConfigurationsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class ConfigurationsResponse {

  @SerializedName("auth_mode")
  private StringConfigItem authMode = null;

  @SerializedName("email_from")
  private StringConfigItem emailFrom = null;

  @SerializedName("email_host")
  private StringConfigItem emailHost = null;

  @SerializedName("email_port")
  private IntegerConfigItem emailPort = null;

  @SerializedName("email_identity")
  private StringConfigItem emailIdentity = null;

  @SerializedName("email_username")
  private StringConfigItem emailUsername = null;

  @SerializedName("email_ssl")
  private BoolConfigItem emailSsl = null;

  @SerializedName("email_insecure")
  private BoolConfigItem emailInsecure = null;

  @SerializedName("ldap_url")
  private StringConfigItem ldapUrl = null;

  @SerializedName("ldap_base_dn")
  private StringConfigItem ldapBaseDn = null;

  @SerializedName("ldap_filter")
  private StringConfigItem ldapFilter = null;

  @SerializedName("ldap_scope")
  private Integer ldapScope = null;

  @SerializedName("ldap_uid")
  private StringConfigItem ldapUid = null;

  @SerializedName("ldap_search_dn")
  private String ldapSearchDn = null;

  @SerializedName("ldap_timeout")
  private IntegerConfigItem ldapTimeout = null;

  @SerializedName("ldap_group_attribute_name")
  private StringConfigItem ldapGroupAttributeName = null;

  @SerializedName("ldap_group_base_dn")
  private StringConfigItem ldapGroupBaseDn = null;

  @SerializedName("ldap_group_search_filter")
  private StringConfigItem ldapGroupSearchFilter = null;

  @SerializedName("ldap_group_search_scope")
  private IntegerConfigItem ldapGroupSearchScope = null;

  @SerializedName("ldap_group_admin_dn")
  private StringConfigItem ldapGroupAdminDn = null;

  @SerializedName("project_creation_restriction")
  private StringConfigItem projectCreationRestriction = null;

  @SerializedName("read_only")
  private BoolConfigItem readOnly = null;

  @SerializedName("self_registration")
  private BoolConfigItem selfRegistration = null;

  @SerializedName("token_expiration")
  private IntegerConfigItem tokenExpiration = null;

  @SerializedName("verify_remote_cert")
  private BoolConfigItem verifyRemoteCert = null;

  @SerializedName("scan_all_policy")
  private Object scanAllPolicy = null;
  public ConfigurationsResponse authMode(StringConfigItem authMode) {
    this.authMode = authMode;
    return this;
  }

  

  /**
  * Get authMode
  * @return authMode
  **/
  @Schema(description = "")
  public StringConfigItem getAuthMode() {
    return authMode;
  }
  public void setAuthMode(StringConfigItem authMode) {
    this.authMode = authMode;
  }
  public ConfigurationsResponse emailFrom(StringConfigItem emailFrom) {
    this.emailFrom = emailFrom;
    return this;
  }

  

  /**
  * Get emailFrom
  * @return emailFrom
  **/
  @Schema(description = "")
  public StringConfigItem getEmailFrom() {
    return emailFrom;
  }
  public void setEmailFrom(StringConfigItem emailFrom) {
    this.emailFrom = emailFrom;
  }
  public ConfigurationsResponse emailHost(StringConfigItem emailHost) {
    this.emailHost = emailHost;
    return this;
  }

  

  /**
  * Get emailHost
  * @return emailHost
  **/
  @Schema(description = "")
  public StringConfigItem getEmailHost() {
    return emailHost;
  }
  public void setEmailHost(StringConfigItem emailHost) {
    this.emailHost = emailHost;
  }
  public ConfigurationsResponse emailPort(IntegerConfigItem emailPort) {
    this.emailPort = emailPort;
    return this;
  }

  

  /**
  * Get emailPort
  * @return emailPort
  **/
  @Schema(description = "")
  public IntegerConfigItem getEmailPort() {
    return emailPort;
  }
  public void setEmailPort(IntegerConfigItem emailPort) {
    this.emailPort = emailPort;
  }
  public ConfigurationsResponse emailIdentity(StringConfigItem emailIdentity) {
    this.emailIdentity = emailIdentity;
    return this;
  }

  

  /**
  * Get emailIdentity
  * @return emailIdentity
  **/
  @Schema(description = "")
  public StringConfigItem getEmailIdentity() {
    return emailIdentity;
  }
  public void setEmailIdentity(StringConfigItem emailIdentity) {
    this.emailIdentity = emailIdentity;
  }
  public ConfigurationsResponse emailUsername(StringConfigItem emailUsername) {
    this.emailUsername = emailUsername;
    return this;
  }

  

  /**
  * Get emailUsername
  * @return emailUsername
  **/
  @Schema(description = "")
  public StringConfigItem getEmailUsername() {
    return emailUsername;
  }
  public void setEmailUsername(StringConfigItem emailUsername) {
    this.emailUsername = emailUsername;
  }
  public ConfigurationsResponse emailSsl(BoolConfigItem emailSsl) {
    this.emailSsl = emailSsl;
    return this;
  }

  

  /**
  * Get emailSsl
  * @return emailSsl
  **/
  @Schema(description = "")
  public BoolConfigItem getEmailSsl() {
    return emailSsl;
  }
  public void setEmailSsl(BoolConfigItem emailSsl) {
    this.emailSsl = emailSsl;
  }
  public ConfigurationsResponse emailInsecure(BoolConfigItem emailInsecure) {
    this.emailInsecure = emailInsecure;
    return this;
  }

  

  /**
  * Get emailInsecure
  * @return emailInsecure
  **/
  @Schema(description = "")
  public BoolConfigItem getEmailInsecure() {
    return emailInsecure;
  }
  public void setEmailInsecure(BoolConfigItem emailInsecure) {
    this.emailInsecure = emailInsecure;
  }
  public ConfigurationsResponse ldapUrl(StringConfigItem ldapUrl) {
    this.ldapUrl = ldapUrl;
    return this;
  }

  

  /**
  * Get ldapUrl
  * @return ldapUrl
  **/
  @Schema(description = "")
  public StringConfigItem getLdapUrl() {
    return ldapUrl;
  }
  public void setLdapUrl(StringConfigItem ldapUrl) {
    this.ldapUrl = ldapUrl;
  }
  public ConfigurationsResponse ldapBaseDn(StringConfigItem ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
    return this;
  }

  

  /**
  * Get ldapBaseDn
  * @return ldapBaseDn
  **/
  @Schema(description = "")
  public StringConfigItem getLdapBaseDn() {
    return ldapBaseDn;
  }
  public void setLdapBaseDn(StringConfigItem ldapBaseDn) {
    this.ldapBaseDn = ldapBaseDn;
  }
  public ConfigurationsResponse ldapFilter(StringConfigItem ldapFilter) {
    this.ldapFilter = ldapFilter;
    return this;
  }

  

  /**
  * Get ldapFilter
  * @return ldapFilter
  **/
  @Schema(description = "")
  public StringConfigItem getLdapFilter() {
    return ldapFilter;
  }
  public void setLdapFilter(StringConfigItem ldapFilter) {
    this.ldapFilter = ldapFilter;
  }
  public ConfigurationsResponse ldapScope(Integer ldapScope) {
    this.ldapScope = ldapScope;
    return this;
  }

  

  /**
  * 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
  * @return ldapScope
  **/
  @Schema(description = "0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE")
  public Integer getLdapScope() {
    return ldapScope;
  }
  public void setLdapScope(Integer ldapScope) {
    this.ldapScope = ldapScope;
  }
  public ConfigurationsResponse ldapUid(StringConfigItem ldapUid) {
    this.ldapUid = ldapUid;
    return this;
  }

  

  /**
  * Get ldapUid
  * @return ldapUid
  **/
  @Schema(description = "")
  public StringConfigItem getLdapUid() {
    return ldapUid;
  }
  public void setLdapUid(StringConfigItem ldapUid) {
    this.ldapUid = ldapUid;
  }
  public ConfigurationsResponse ldapSearchDn(String ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
    return this;
  }

  

  /**
  * The DN of the user to do the search.
  * @return ldapSearchDn
  **/
  @Schema(description = "The DN of the user to do the search.")
  public String getLdapSearchDn() {
    return ldapSearchDn;
  }
  public void setLdapSearchDn(String ldapSearchDn) {
    this.ldapSearchDn = ldapSearchDn;
  }
  public ConfigurationsResponse ldapTimeout(IntegerConfigItem ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
    return this;
  }

  

  /**
  * Get ldapTimeout
  * @return ldapTimeout
  **/
  @Schema(description = "")
  public IntegerConfigItem getLdapTimeout() {
    return ldapTimeout;
  }
  public void setLdapTimeout(IntegerConfigItem ldapTimeout) {
    this.ldapTimeout = ldapTimeout;
  }
  public ConfigurationsResponse ldapGroupAttributeName(StringConfigItem ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
    return this;
  }

  

  /**
  * Get ldapGroupAttributeName
  * @return ldapGroupAttributeName
  **/
  @Schema(description = "")
  public StringConfigItem getLdapGroupAttributeName() {
    return ldapGroupAttributeName;
  }
  public void setLdapGroupAttributeName(StringConfigItem ldapGroupAttributeName) {
    this.ldapGroupAttributeName = ldapGroupAttributeName;
  }
  public ConfigurationsResponse ldapGroupBaseDn(StringConfigItem ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
    return this;
  }

  

  /**
  * Get ldapGroupBaseDn
  * @return ldapGroupBaseDn
  **/
  @Schema(description = "")
  public StringConfigItem getLdapGroupBaseDn() {
    return ldapGroupBaseDn;
  }
  public void setLdapGroupBaseDn(StringConfigItem ldapGroupBaseDn) {
    this.ldapGroupBaseDn = ldapGroupBaseDn;
  }
  public ConfigurationsResponse ldapGroupSearchFilter(StringConfigItem ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
    return this;
  }

  

  /**
  * Get ldapGroupSearchFilter
  * @return ldapGroupSearchFilter
  **/
  @Schema(description = "")
  public StringConfigItem getLdapGroupSearchFilter() {
    return ldapGroupSearchFilter;
  }
  public void setLdapGroupSearchFilter(StringConfigItem ldapGroupSearchFilter) {
    this.ldapGroupSearchFilter = ldapGroupSearchFilter;
  }
  public ConfigurationsResponse ldapGroupSearchScope(IntegerConfigItem ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
    return this;
  }

  

  /**
  * Get ldapGroupSearchScope
  * @return ldapGroupSearchScope
  **/
  @Schema(description = "")
  public IntegerConfigItem getLdapGroupSearchScope() {
    return ldapGroupSearchScope;
  }
  public void setLdapGroupSearchScope(IntegerConfigItem ldapGroupSearchScope) {
    this.ldapGroupSearchScope = ldapGroupSearchScope;
  }
  public ConfigurationsResponse ldapGroupAdminDn(StringConfigItem ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
    return this;
  }

  

  /**
  * Get ldapGroupAdminDn
  * @return ldapGroupAdminDn
  **/
  @Schema(description = "")
  public StringConfigItem getLdapGroupAdminDn() {
    return ldapGroupAdminDn;
  }
  public void setLdapGroupAdminDn(StringConfigItem ldapGroupAdminDn) {
    this.ldapGroupAdminDn = ldapGroupAdminDn;
  }
  public ConfigurationsResponse projectCreationRestriction(StringConfigItem projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
    return this;
  }

  

  /**
  * Get projectCreationRestriction
  * @return projectCreationRestriction
  **/
  @Schema(description = "")
  public StringConfigItem getProjectCreationRestriction() {
    return projectCreationRestriction;
  }
  public void setProjectCreationRestriction(StringConfigItem projectCreationRestriction) {
    this.projectCreationRestriction = projectCreationRestriction;
  }
  public ConfigurationsResponse readOnly(BoolConfigItem readOnly) {
    this.readOnly = readOnly;
    return this;
  }

  

  /**
  * Get readOnly
  * @return readOnly
  **/
  @Schema(description = "")
  public BoolConfigItem getReadOnly() {
    return readOnly;
  }
  public void setReadOnly(BoolConfigItem readOnly) {
    this.readOnly = readOnly;
  }
  public ConfigurationsResponse selfRegistration(BoolConfigItem selfRegistration) {
    this.selfRegistration = selfRegistration;
    return this;
  }

  

  /**
  * Get selfRegistration
  * @return selfRegistration
  **/
  @Schema(description = "")
  public BoolConfigItem getSelfRegistration() {
    return selfRegistration;
  }
  public void setSelfRegistration(BoolConfigItem selfRegistration) {
    this.selfRegistration = selfRegistration;
  }
  public ConfigurationsResponse tokenExpiration(IntegerConfigItem tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
    return this;
  }

  

  /**
  * Get tokenExpiration
  * @return tokenExpiration
  **/
  @Schema(description = "")
  public IntegerConfigItem getTokenExpiration() {
    return tokenExpiration;
  }
  public void setTokenExpiration(IntegerConfigItem tokenExpiration) {
    this.tokenExpiration = tokenExpiration;
  }
  public ConfigurationsResponse verifyRemoteCert(BoolConfigItem verifyRemoteCert) {
    this.verifyRemoteCert = verifyRemoteCert;
    return this;
  }

  

  /**
  * Get verifyRemoteCert
  * @return verifyRemoteCert
  **/
  @Schema(description = "")
  public BoolConfigItem getVerifyRemoteCert() {
    return verifyRemoteCert;
  }
  public void setVerifyRemoteCert(BoolConfigItem verifyRemoteCert) {
    this.verifyRemoteCert = verifyRemoteCert;
  }
  public ConfigurationsResponse scanAllPolicy(Object scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
    return this;
  }

  

  /**
  * Get scanAllPolicy
  * @return scanAllPolicy
  **/
  @Schema(description = "")
  public Object getScanAllPolicy() {
    return scanAllPolicy;
  }
  public void setScanAllPolicy(Object scanAllPolicy) {
    this.scanAllPolicy = scanAllPolicy;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationsResponse configurationsResponse = (ConfigurationsResponse) o;
    return Objects.equals(this.authMode, configurationsResponse.authMode) &&
        Objects.equals(this.emailFrom, configurationsResponse.emailFrom) &&
        Objects.equals(this.emailHost, configurationsResponse.emailHost) &&
        Objects.equals(this.emailPort, configurationsResponse.emailPort) &&
        Objects.equals(this.emailIdentity, configurationsResponse.emailIdentity) &&
        Objects.equals(this.emailUsername, configurationsResponse.emailUsername) &&
        Objects.equals(this.emailSsl, configurationsResponse.emailSsl) &&
        Objects.equals(this.emailInsecure, configurationsResponse.emailInsecure) &&
        Objects.equals(this.ldapUrl, configurationsResponse.ldapUrl) &&
        Objects.equals(this.ldapBaseDn, configurationsResponse.ldapBaseDn) &&
        Objects.equals(this.ldapFilter, configurationsResponse.ldapFilter) &&
        Objects.equals(this.ldapScope, configurationsResponse.ldapScope) &&
        Objects.equals(this.ldapUid, configurationsResponse.ldapUid) &&
        Objects.equals(this.ldapSearchDn, configurationsResponse.ldapSearchDn) &&
        Objects.equals(this.ldapTimeout, configurationsResponse.ldapTimeout) &&
        Objects.equals(this.ldapGroupAttributeName, configurationsResponse.ldapGroupAttributeName) &&
        Objects.equals(this.ldapGroupBaseDn, configurationsResponse.ldapGroupBaseDn) &&
        Objects.equals(this.ldapGroupSearchFilter, configurationsResponse.ldapGroupSearchFilter) &&
        Objects.equals(this.ldapGroupSearchScope, configurationsResponse.ldapGroupSearchScope) &&
        Objects.equals(this.ldapGroupAdminDn, configurationsResponse.ldapGroupAdminDn) &&
        Objects.equals(this.projectCreationRestriction, configurationsResponse.projectCreationRestriction) &&
        Objects.equals(this.readOnly, configurationsResponse.readOnly) &&
        Objects.equals(this.selfRegistration, configurationsResponse.selfRegistration) &&
        Objects.equals(this.tokenExpiration, configurationsResponse.tokenExpiration) &&
        Objects.equals(this.verifyRemoteCert, configurationsResponse.verifyRemoteCert) &&
        Objects.equals(this.scanAllPolicy, configurationsResponse.scanAllPolicy);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(authMode, emailFrom, emailHost, emailPort, emailIdentity, emailUsername, emailSsl, emailInsecure, ldapUrl, ldapBaseDn, ldapFilter, ldapScope, ldapUid, ldapSearchDn, ldapTimeout, ldapGroupAttributeName, ldapGroupBaseDn, ldapGroupSearchFilter, ldapGroupSearchScope, ldapGroupAdminDn, projectCreationRestriction, readOnly, selfRegistration, tokenExpiration, verifyRemoteCert, scanAllPolicy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationsResponse {\n");
    
    sb.append("    authMode: ").append(toIndentedString(authMode)).append("\n");
    sb.append("    emailFrom: ").append(toIndentedString(emailFrom)).append("\n");
    sb.append("    emailHost: ").append(toIndentedString(emailHost)).append("\n");
    sb.append("    emailPort: ").append(toIndentedString(emailPort)).append("\n");
    sb.append("    emailIdentity: ").append(toIndentedString(emailIdentity)).append("\n");
    sb.append("    emailUsername: ").append(toIndentedString(emailUsername)).append("\n");
    sb.append("    emailSsl: ").append(toIndentedString(emailSsl)).append("\n");
    sb.append("    emailInsecure: ").append(toIndentedString(emailInsecure)).append("\n");
    sb.append("    ldapUrl: ").append(toIndentedString(ldapUrl)).append("\n");
    sb.append("    ldapBaseDn: ").append(toIndentedString(ldapBaseDn)).append("\n");
    sb.append("    ldapFilter: ").append(toIndentedString(ldapFilter)).append("\n");
    sb.append("    ldapScope: ").append(toIndentedString(ldapScope)).append("\n");
    sb.append("    ldapUid: ").append(toIndentedString(ldapUid)).append("\n");
    sb.append("    ldapSearchDn: ").append(toIndentedString(ldapSearchDn)).append("\n");
    sb.append("    ldapTimeout: ").append(toIndentedString(ldapTimeout)).append("\n");
    sb.append("    ldapGroupAttributeName: ").append(toIndentedString(ldapGroupAttributeName)).append("\n");
    sb.append("    ldapGroupBaseDn: ").append(toIndentedString(ldapGroupBaseDn)).append("\n");
    sb.append("    ldapGroupSearchFilter: ").append(toIndentedString(ldapGroupSearchFilter)).append("\n");
    sb.append("    ldapGroupSearchScope: ").append(toIndentedString(ldapGroupSearchScope)).append("\n");
    sb.append("    ldapGroupAdminDn: ").append(toIndentedString(ldapGroupAdminDn)).append("\n");
    sb.append("    projectCreationRestriction: ").append(toIndentedString(projectCreationRestriction)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    selfRegistration: ").append(toIndentedString(selfRegistration)).append("\n");
    sb.append("    tokenExpiration: ").append(toIndentedString(tokenExpiration)).append("\n");
    sb.append("    verifyRemoteCert: ").append(toIndentedString(verifyRemoteCert)).append("\n");
    sb.append("    scanAllPolicy: ").append(toIndentedString(scanAllPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
