/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.Label;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DetailedTag
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class DetailedTag {

  @SerializedName("digest")
  private String digest = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("architecture")
  private String architecture = null;

  @SerializedName("os")
  private String os = null;

  @SerializedName("docker_version")
  private String dockerVersion = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("signature")
  private Object signature = null;

  @SerializedName("scan_overview")
  private Object scanOverview = null;

  @SerializedName("labels")
  private List<Label> labels = null;
  public DetailedTag digest(String digest) {
    this.digest = digest;
    return this;
  }

  

  /**
  * The digest of the tag.
  * @return digest
  **/
  @Schema(description = "The digest of the tag.")
  public String getDigest() {
    return digest;
  }
  public void setDigest(String digest) {
    this.digest = digest;
  }
  public DetailedTag name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the tag.
  * @return name
  **/
  @Schema(description = "The name of the tag.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public DetailedTag size(Integer size) {
    this.size = size;
    return this;
  }

  

  /**
  * The size of the image.
  * @return size
  **/
  @Schema(description = "The size of the image.")
  public Integer getSize() {
    return size;
  }
  public void setSize(Integer size) {
    this.size = size;
  }
  public DetailedTag architecture(String architecture) {
    this.architecture = architecture;
    return this;
  }

  

  /**
  * The architecture of the image.
  * @return architecture
  **/
  @Schema(description = "The architecture of the image.")
  public String getArchitecture() {
    return architecture;
  }
  public void setArchitecture(String architecture) {
    this.architecture = architecture;
  }
  public DetailedTag os(String os) {
    this.os = os;
    return this;
  }

  

  /**
  * The os of the image.
  * @return os
  **/
  @Schema(description = "The os of the image.")
  public String getOs() {
    return os;
  }
  public void setOs(String os) {
    this.os = os;
  }
  public DetailedTag dockerVersion(String dockerVersion) {
    this.dockerVersion = dockerVersion;
    return this;
  }

  

  /**
  * The version of docker which builds the image.
  * @return dockerVersion
  **/
  @Schema(description = "The version of docker which builds the image.")
  public String getDockerVersion() {
    return dockerVersion;
  }
  public void setDockerVersion(String dockerVersion) {
    this.dockerVersion = dockerVersion;
  }
  public DetailedTag author(String author) {
    this.author = author;
    return this;
  }

  

  /**
  * The author of the image.
  * @return author
  **/
  @Schema(description = "The author of the image.")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }
  public DetailedTag created(String created) {
    this.created = created;
    return this;
  }

  

  /**
  * The build time of the image.
  * @return created
  **/
  @Schema(description = "The build time of the image.")
  public String getCreated() {
    return created;
  }
  public void setCreated(String created) {
    this.created = created;
  }
  public DetailedTag signature(Object signature) {
    this.signature = signature;
    return this;
  }

  

  /**
  * The signature of image, defined by RepoSignature. If it is null, the image is unsigned.
  * @return signature
  **/
  @Schema(description = "The signature of image, defined by RepoSignature. If it is null, the image is unsigned.")
  public Object getSignature() {
    return signature;
  }
  public void setSignature(Object signature) {
    this.signature = signature;
  }
  public DetailedTag scanOverview(Object scanOverview) {
    this.scanOverview = scanOverview;
    return this;
  }

  

  /**
  * The overview of the scan result.  This is an optional property.
  * @return scanOverview
  **/
  @Schema(description = "The overview of the scan result.  This is an optional property.")
  public Object getScanOverview() {
    return scanOverview;
  }
  public void setScanOverview(Object scanOverview) {
    this.scanOverview = scanOverview;
  }
  public DetailedTag labels(List<Label> labels) {
    this.labels = labels;
    return this;
  }

  public DetailedTag addLabelsItem(Label labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<Label>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
  * The label list.
  * @return labels
  **/
  @Schema(description = "The label list.")
  public List<Label> getLabels() {
    return labels;
  }
  public void setLabels(List<Label> labels) {
    this.labels = labels;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedTag detailedTag = (DetailedTag) o;
    return Objects.equals(this.digest, detailedTag.digest) &&
        Objects.equals(this.name, detailedTag.name) &&
        Objects.equals(this.size, detailedTag.size) &&
        Objects.equals(this.architecture, detailedTag.architecture) &&
        Objects.equals(this.os, detailedTag.os) &&
        Objects.equals(this.dockerVersion, detailedTag.dockerVersion) &&
        Objects.equals(this.author, detailedTag.author) &&
        Objects.equals(this.created, detailedTag.created) &&
        Objects.equals(this.signature, detailedTag.signature) &&
        Objects.equals(this.scanOverview, detailedTag.scanOverview) &&
        Objects.equals(this.labels, detailedTag.labels);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(digest, name, size, architecture, os, dockerVersion, author, created, signature, scanOverview, labels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedTag {\n");
    
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    architecture: ").append(toIndentedString(architecture)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    dockerVersion: ").append(toIndentedString(dockerVersion)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    scanOverview: ").append(toIndentedString(scanOverview)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
