/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * GCScheduleSchedule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class GCScheduleSchedule {

  @SerializedName("type")
  private String type = null;

  @SerializedName("weekday")
  private Integer weekday = null;

  @SerializedName("offtime")
  private Long offtime = null;
  public GCScheduleSchedule type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * The schedule type. The valid values are daily， weekly and None. &#x27;None&#x27; means to cancel the schedule.
  * @return type
  **/
  @Schema(description = "The schedule type. The valid values are daily， weekly and None. 'None' means to cancel the schedule.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public GCScheduleSchedule weekday(Integer weekday) {
    this.weekday = weekday;
    return this;
  }

  

  /**
  * Optional, only used when the type is weekly. The valid values are 1-7.
  * @return weekday
  **/
  @Schema(description = "Optional, only used when the type is weekly. The valid values are 1-7.")
  public Integer getWeekday() {
    return weekday;
  }
  public void setWeekday(Integer weekday) {
    this.weekday = weekday;
  }
  public GCScheduleSchedule offtime(Long offtime) {
    this.offtime = offtime;
    return this;
  }

  

  /**
  * The time offset with the UTC 00:00 in seconds.
  * @return offtime
  **/
  @Schema(description = "The time offset with the UTC 00:00 in seconds.")
  public Long getOfftime() {
    return offtime;
  }
  public void setOfftime(Long offtime) {
    this.offtime = offtime;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GCScheduleSchedule gcScheduleSchedule = (GCScheduleSchedule) o;
    return Objects.equals(this.type, gcScheduleSchedule.type) &&
        Objects.equals(this.weekday, gcScheduleSchedule.weekday) &&
        Objects.equals(this.offtime, gcScheduleSchedule.offtime);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(type, weekday, offtime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GCScheduleSchedule {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    weekday: ").append(toIndentedString(weekday)).append("\n");
    sb.append("    offtime: ").append(toIndentedString(offtime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
