/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.GCScheduleSchedule;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * GCSchedule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class GCSchedule {

  @SerializedName("schedule")
  private GCScheduleSchedule schedule = null;
  public GCSchedule schedule(GCScheduleSchedule schedule) {
    this.schedule = schedule;
    return this;
  }

  

  /**
  * Get schedule
  * @return schedule
  **/
  @Schema(description = "")
  public GCScheduleSchedule getSchedule() {
    return schedule;
  }
  public void setSchedule(GCScheduleSchedule schedule) {
    this.schedule = schedule;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GCSchedule gcSchedule = (GCSchedule) o;
    return Objects.equals(this.schedule, gcSchedule.schedule);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(schedule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GCSchedule {\n");
    
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
