/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * HasAdminRole
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class HasAdminRole {

  @SerializedName("has_admin_role")
  private Boolean hasAdminRole = null;
  public HasAdminRole hasAdminRole(Boolean hasAdminRole) {
    this.hasAdminRole = hasAdminRole;
    return this;
  }

  

  /**
  * 1-has admin, 0-not.
  * @return hasAdminRole
  **/
  @Schema(description = "1-has admin, 0-not.")
  public Boolean isHasAdminRole() {
    return hasAdminRole;
  }
  public void setHasAdminRole(Boolean hasAdminRole) {
    this.hasAdminRole = hasAdminRole;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HasAdminRole hasAdminRole = (HasAdminRole) o;
    return Objects.equals(this.hasAdminRole, hasAdminRole.hasAdminRole);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(hasAdminRole);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HasAdminRole {\n");
    
    sb.append("    hasAdminRole: ").append(toIndentedString(hasAdminRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
