/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * LdapUsers
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class LdapUsers {

  @SerializedName("ldap_username")
  private String ldapUsername = null;

  @SerializedName("ldap_realname")
  private String ldapRealname = null;

  @SerializedName("ldap_email")
  private String ldapEmail = null;
  public LdapUsers ldapUsername(String ldapUsername) {
    this.ldapUsername = ldapUsername;
    return this;
  }

  

  /**
  * search ldap user name based on ldapconf.
  * @return ldapUsername
  **/
  @Schema(description = "search ldap user name based on ldapconf.")
  public String getLdapUsername() {
    return ldapUsername;
  }
  public void setLdapUsername(String ldapUsername) {
    this.ldapUsername = ldapUsername;
  }
  public LdapUsers ldapRealname(String ldapRealname) {
    this.ldapRealname = ldapRealname;
    return this;
  }

  

  /**
  * system will try to guess the user realname form \&quot;uid\&quot; or \&quot;cn\&quot; attribute.
  * @return ldapRealname
  **/
  @Schema(description = "system will try to guess the user realname form \"uid\" or \"cn\" attribute.")
  public String getLdapRealname() {
    return ldapRealname;
  }
  public void setLdapRealname(String ldapRealname) {
    this.ldapRealname = ldapRealname;
  }
  public LdapUsers ldapEmail(String ldapEmail) {
    this.ldapEmail = ldapEmail;
    return this;
  }

  

  /**
  * system will try to guess the user email address form \&quot;mail\&quot; or \&quot;email\&quot; attribute.
  * @return ldapEmail
  **/
  @Schema(description = "system will try to guess the user email address form \"mail\" or \"email\" attribute.")
  public String getLdapEmail() {
    return ldapEmail;
  }
  public void setLdapEmail(String ldapEmail) {
    this.ldapEmail = ldapEmail;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LdapUsers ldapUsers = (LdapUsers) o;
    return Objects.equals(this.ldapUsername, ldapUsers.ldapUsername) &&
        Objects.equals(this.ldapRealname, ldapUsers.ldapRealname) &&
        Objects.equals(this.ldapEmail, ldapUsers.ldapEmail);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(ldapUsername, ldapRealname, ldapEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LdapUsers {\n");
    
    sb.append("    ldapUsername: ").append(toIndentedString(ldapUsername)).append("\n");
    sb.append("    ldapRealname: ").append(toIndentedString(ldapRealname)).append("\n");
    sb.append("    ldapEmail: ").append(toIndentedString(ldapEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
