/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Manifest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class Manifest {

  @SerializedName("manifest")
  private Object manifest = null;

  @SerializedName("config")
  private String config = null;
  public Manifest manifest(Object manifest) {
    this.manifest = manifest;
    return this;
  }

  

  /**
  * The detail of manifest.
  * @return manifest
  **/
  @Schema(description = "The detail of manifest.")
  public Object getManifest() {
    return manifest;
  }
  public void setManifest(Object manifest) {
    this.manifest = manifest;
  }
  public Manifest config(String config) {
    this.config = config;
    return this;
  }

  

  /**
  * The config of the repository.
  * @return config
  **/
  @Schema(description = "The config of the repository.")
  public String getConfig() {
    return config;
  }
  public void setConfig(String config) {
    this.config = config;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Manifest manifest = (Manifest) o;
    return Objects.equals(this.manifest, manifest.manifest) &&
        Objects.equals(this.config, manifest.config);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(manifest, config);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Manifest {\n");
    
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
