/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ProjectMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class ProjectMetadata {

  @SerializedName("public")
  private String _public = null;

  @SerializedName("enable_content_trust")
  private String enableContentTrust = null;

  @SerializedName("prevent_vul")
  private String preventVul = null;

  @SerializedName("severity")
  private String severity = null;

  @SerializedName("auto_scan")
  private String autoScan = null;
  public ProjectMetadata _public(String _public) {
    this._public = _public;
    return this;
  }

  

  /**
  * The public status of the project. The valid values are \&quot;true\&quot;, \&quot;false\&quot;.
  * @return _public
  **/
  @Schema(description = "The public status of the project. The valid values are \"true\", \"false\".")
  public String getPublic() {
    return _public;
  }
  public void setPublic(String _public) {
    this._public = _public;
  }
  public ProjectMetadata enableContentTrust(String enableContentTrust) {
    this.enableContentTrust = enableContentTrust;
    return this;
  }

  

  /**
  * Whether content trust is enabled or not. If it is enabled, user cann&#x27;t pull unsigned images from this project. The valid values are \&quot;true\&quot;, \&quot;false\&quot;.
  * @return enableContentTrust
  **/
  @Schema(description = "Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project. The valid values are \"true\", \"false\".")
  public String getEnableContentTrust() {
    return enableContentTrust;
  }
  public void setEnableContentTrust(String enableContentTrust) {
    this.enableContentTrust = enableContentTrust;
  }
  public ProjectMetadata preventVul(String preventVul) {
    this.preventVul = preventVul;
    return this;
  }

  

  /**
  * Whether prevent the vulnerable images from running. The valid values are \&quot;true\&quot;, \&quot;false\&quot;.
  * @return preventVul
  **/
  @Schema(description = "Whether prevent the vulnerable images from running. The valid values are \"true\", \"false\".")
  public String getPreventVul() {
    return preventVul;
  }
  public void setPreventVul(String preventVul) {
    this.preventVul = preventVul;
  }
  public ProjectMetadata severity(String severity) {
    this.severity = severity;
    return this;
  }

  

  /**
  * If the vulnerability is high than severity defined here, the images cann&#x27;t be pulled. The valid values are \&quot;negligible\&quot;, \&quot;low\&quot;, \&quot;medium\&quot;, \&quot;high\&quot;, \&quot;critical\&quot;.
  * @return severity
  **/
  @Schema(description = "If the vulnerability is high than severity defined here, the images cann't be pulled. The valid values are \"negligible\", \"low\", \"medium\", \"high\", \"critical\".")
  public String getSeverity() {
    return severity;
  }
  public void setSeverity(String severity) {
    this.severity = severity;
  }
  public ProjectMetadata autoScan(String autoScan) {
    this.autoScan = autoScan;
    return this;
  }

  

  /**
  * Whether scan images automatically when pushing. The valid values are \&quot;true\&quot;, \&quot;false\&quot;.
  * @return autoScan
  **/
  @Schema(description = "Whether scan images automatically when pushing. The valid values are \"true\", \"false\".")
  public String getAutoScan() {
    return autoScan;
  }
  public void setAutoScan(String autoScan) {
    this.autoScan = autoScan;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectMetadata projectMetadata = (ProjectMetadata) o;
    return Objects.equals(this._public, projectMetadata._public) &&
        Objects.equals(this.enableContentTrust, projectMetadata.enableContentTrust) &&
        Objects.equals(this.preventVul, projectMetadata.preventVul) &&
        Objects.equals(this.severity, projectMetadata.severity) &&
        Objects.equals(this.autoScan, projectMetadata.autoScan);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(_public, enableContentTrust, preventVul, severity, autoScan);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectMetadata {\n");
    
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    enableContentTrust: ").append(toIndentedString(enableContentTrust)).append("\n");
    sb.append("    preventVul: ").append(toIndentedString(preventVul)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    autoScan: ").append(toIndentedString(autoScan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
