/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.ProjectMetadata;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Project
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class Project {

  @SerializedName("project_id")
  private Integer projectId = null;

  @SerializedName("owner_id")
  private Integer ownerId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("creation_time")
  private String creationTime = null;

  @SerializedName("update_time")
  private String updateTime = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  @SerializedName("owner_name")
  private String ownerName = null;

  @SerializedName("togglable")
  private Boolean togglable = null;

  @SerializedName("current_user_role_id")
  private Integer currentUserRoleId = null;

  @SerializedName("repo_count")
  private Integer repoCount = null;

  @SerializedName("chart_count")
  private Integer chartCount = null;

  @SerializedName("metadata")
  private ProjectMetadata metadata = null;
  public Project projectId(Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  

  /**
  * Project ID
  * @return projectId
  **/
  @Schema(description = "Project ID")
  public Integer getProjectId() {
    return projectId;
  }
  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }
  public Project ownerId(Integer ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  

  /**
  * The owner ID of the project always means the creator of the project.
  * @return ownerId
  **/
  @Schema(description = "The owner ID of the project always means the creator of the project.")
  public Integer getOwnerId() {
    return ownerId;
  }
  public void setOwnerId(Integer ownerId) {
    this.ownerId = ownerId;
  }
  public Project name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the project.
  * @return name
  **/
  @Schema(description = "The name of the project.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Project creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

  

  /**
  * The creation time of the project.
  * @return creationTime
  **/
  @Schema(description = "The creation time of the project.")
  public String getCreationTime() {
    return creationTime;
  }
  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }
  public Project updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  

  /**
  * The update time of the project.
  * @return updateTime
  **/
  @Schema(description = "The update time of the project.")
  public String getUpdateTime() {
    return updateTime;
  }
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }
  public Project deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  

  /**
  * A deletion mark of the project.
  * @return deleted
  **/
  @Schema(description = "A deletion mark of the project.")
  public Boolean isDeleted() {
    return deleted;
  }
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }
  public Project ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

  

  /**
  * The owner name of the project.
  * @return ownerName
  **/
  @Schema(description = "The owner name of the project.")
  public String getOwnerName() {
    return ownerName;
  }
  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }
  public Project togglable(Boolean togglable) {
    this.togglable = togglable;
    return this;
  }

  

  /**
  * Correspond to the UI about whether the project&#x27;s publicity is  updatable (for UI)
  * @return togglable
  **/
  @Schema(description = "Correspond to the UI about whether the project's publicity is  updatable (for UI)")
  public Boolean isTogglable() {
    return togglable;
  }
  public void setTogglable(Boolean togglable) {
    this.togglable = togglable;
  }
  public Project currentUserRoleId(Integer currentUserRoleId) {
    this.currentUserRoleId = currentUserRoleId;
    return this;
  }

  

  /**
  * The role ID of the current user who triggered the API (for UI)
  * @return currentUserRoleId
  **/
  @Schema(description = "The role ID of the current user who triggered the API (for UI)")
  public Integer getCurrentUserRoleId() {
    return currentUserRoleId;
  }
  public void setCurrentUserRoleId(Integer currentUserRoleId) {
    this.currentUserRoleId = currentUserRoleId;
  }
  public Project repoCount(Integer repoCount) {
    this.repoCount = repoCount;
    return this;
  }

  

  /**
  * The number of the repositories under this project.
  * @return repoCount
  **/
  @Schema(description = "The number of the repositories under this project.")
  public Integer getRepoCount() {
    return repoCount;
  }
  public void setRepoCount(Integer repoCount) {
    this.repoCount = repoCount;
  }
  public Project chartCount(Integer chartCount) {
    this.chartCount = chartCount;
    return this;
  }

  

  /**
  * The total number of charts under this project.
  * @return chartCount
  **/
  @Schema(description = "The total number of charts under this project.")
  public Integer getChartCount() {
    return chartCount;
  }
  public void setChartCount(Integer chartCount) {
    this.chartCount = chartCount;
  }
  public Project metadata(ProjectMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  

  /**
  * Get metadata
  * @return metadata
  **/
  @Schema(description = "")
  public ProjectMetadata getMetadata() {
    return metadata;
  }
  public void setMetadata(ProjectMetadata metadata) {
    this.metadata = metadata;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Project project = (Project) o;
    return Objects.equals(this.projectId, project.projectId) &&
        Objects.equals(this.ownerId, project.ownerId) &&
        Objects.equals(this.name, project.name) &&
        Objects.equals(this.creationTime, project.creationTime) &&
        Objects.equals(this.updateTime, project.updateTime) &&
        Objects.equals(this.deleted, project.deleted) &&
        Objects.equals(this.ownerName, project.ownerName) &&
        Objects.equals(this.togglable, project.togglable) &&
        Objects.equals(this.currentUserRoleId, project.currentUserRoleId) &&
        Objects.equals(this.repoCount, project.repoCount) &&
        Objects.equals(this.chartCount, project.chartCount) &&
        Objects.equals(this.metadata, project.metadata);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(projectId, ownerId, name, creationTime, updateTime, deleted, ownerName, togglable, currentUserRoleId, repoCount, chartCount, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Project {\n");
    
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    togglable: ").append(toIndentedString(togglable)).append("\n");
    sb.append("    currentUserRoleId: ").append(toIndentedString(currentUserRoleId)).append("\n");
    sb.append("    repoCount: ").append(toIndentedString(repoCount)).append("\n");
    sb.append("    chartCount: ").append(toIndentedString(chartCount)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
