/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.ScheduleParam;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * RepTrigger
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class RepTrigger {

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("schedule_param")
  private ScheduleParam scheduleParam = null;
  public RepTrigger kind(String kind) {
    this.kind = kind;
    return this;
  }

  

  /**
  * The replication policy trigger kind. The valid values are manual, immediate and schedule.
  * @return kind
  **/
  @Schema(description = "The replication policy trigger kind. The valid values are manual, immediate and schedule.")
  public String getKind() {
    return kind;
  }
  public void setKind(String kind) {
    this.kind = kind;
  }
  public RepTrigger scheduleParam(ScheduleParam scheduleParam) {
    this.scheduleParam = scheduleParam;
    return this;
  }

  

  /**
  * Get scheduleParam
  * @return scheduleParam
  **/
  @Schema(description = "")
  public ScheduleParam getScheduleParam() {
    return scheduleParam;
  }
  public void setScheduleParam(ScheduleParam scheduleParam) {
    this.scheduleParam = scheduleParam;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepTrigger repTrigger = (RepTrigger) o;
    return Objects.equals(this.kind, repTrigger.kind) &&
        Objects.equals(this.scheduleParam, repTrigger.scheduleParam);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kind, scheduleParam);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepTrigger {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    scheduleParam: ").append(toIndentedString(scheduleParam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
