/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.imwyh.harbor.client.model.DigitalSignature;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * The security information of the chart
 */
@Schema(description = "The security information of the chart")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class SecurityReport {

  @SerializedName("signature")
  private DigitalSignature signature = null;
  public SecurityReport signature(DigitalSignature signature) {
    this.signature = signature;
    return this;
  }

  

  /**
  * Get signature
  * @return signature
  **/
  @Schema(description = "")
  public DigitalSignature getSignature() {
    return signature;
  }
  public void setSignature(DigitalSignature signature) {
    this.signature = signature;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityReport securityReport = (SecurityReport) o;
    return Objects.equals(this.signature, securityReport.signature);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityReport {\n");
    
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
