/*
 * Harbor API
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.imwyh.harbor.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * VulnNamespaceTimestamp
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T14:29:11.153+08:00[Asia/Shanghai]")public class VulnNamespaceTimestamp {

  @SerializedName("namespace")
  private String namespace = null;

  @SerializedName("last_update")
  private Integer lastUpdate = null;
  public VulnNamespaceTimestamp namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

  

  /**
  * The namespace of the Vulnerability
  * @return namespace
  **/
  @Schema(description = "The namespace of the Vulnerability")
  public String getNamespace() {
    return namespace;
  }
  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }
  public VulnNamespaceTimestamp lastUpdate(Integer lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  

  /**
  * The UTC timestamp in miliseconds of last successful update for vulnerability data.
  * @return lastUpdate
  **/
  @Schema(description = "The UTC timestamp in miliseconds of last successful update for vulnerability data.")
  public Integer getLastUpdate() {
    return lastUpdate;
  }
  public void setLastUpdate(Integer lastUpdate) {
    this.lastUpdate = lastUpdate;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VulnNamespaceTimestamp vulnNamespaceTimestamp = (VulnNamespaceTimestamp) o;
    return Objects.equals(this.namespace, vulnNamespaceTimestamp.namespace) &&
        Objects.equals(this.lastUpdate, vulnNamespaceTimestamp.lastUpdate);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(namespace, lastUpdate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VulnNamespaceTimestamp {\n");
    
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
